version: 0.0
os: linux
files:
  - source: /
    destination: /home/bitnami/Django # 배포할 디렉터리 경로
# hooks:
#   AfterInstall:
#     - location: scripts/after_install.sh
#       timeout: 300
#       runas: root
