# Generated by Django 5.0.7 on 2024-07-22 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CheapestProduct',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ingredient_id', models.IntegerField()),
                ('ingredient', models.CharField(max_length=128)),
                ('product_url', models.CharField(blank=True, max_length=2048, null=True)),
                ('unit_price', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'cheapest_product',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CheapRecipe',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('recipe_id', models.IntegerField()),
                ('menu', models.CharField(max_length=64)),
                ('youtube_url', models.CharField(max_length=1024)),
                ('min_total_price', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'cheap_recipe',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('product_id', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(max_length=64)),
                ('quantity', models.FloatField(blank=True, null=True)),
                ('unit', models.CharField(blank=True, max_length=32, null=True)),
                ('vague', models.CharField(blank=True, max_length=64, null=True)),
            ],
            options={
                'db_table': 'ingredient',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('category', models.CharField(blank=True, max_length=64, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'menu',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=1024)),
                ('unit_price', models.FloatField(blank=True, null=True)),
                ('unit', models.CharField(blank=True, max_length=32, null=True)),
                ('url', models.CharField(blank=True, max_length=2048, null=True)),
                ('img_src', models.CharField(blank=True, max_length=2048, null=True)),
                ('badge_rocket', models.CharField(blank=True, max_length=64, null=True)),
                ('storage_method', models.CharField(blank=True, max_length=128, null=True)),
                ('expiration_date', models.DateField(blank=True, null=True)),
                ('is_bulk', models.BooleanField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'product',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='QuantityConversion',
            fields=[
                ('conversion_id', models.AutoField(primary_key=True, serialize=False)),
                ('ingredient_name', models.CharField(blank=True, max_length=64, null=True)),
                ('unit_name', models.CharField(blank=True, max_length=32, null=True)),
                ('converted_gram', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'quantity_conversion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('portions', models.SmallIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'recipe',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RecipeIngredient',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'recipe_ingredient',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UnitConversion',
            fields=[
                ('conversion_id', models.AutoField(primary_key=True, serialize=False)),
                ('standard_unit', models.CharField(blank=True, max_length=32, null=True)),
                ('converted_vol', models.FloatField(blank=True, null=True)),
                ('unit_name', models.CharField(blank=True, max_length=32, null=True)),
            ],
            options={
                'db_table': 'unit_conversion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='YoutubeVdo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('youtube_url', models.CharField(max_length=256)),
                ('full_text', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'youtube_vdo',
                'managed': False,
            },
        ),
    ]
