# Generated by Django 5.0.7 on 2024-07-24 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_authgroup_authgrouppermissions_authpermission_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CheapestProduct',
        ),
    ]
