# Generated by Django 5.1 on 2024-08-24 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0003_delete_cheapestproduct'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RecipeIngredient',
        ),
    ]
