# Generated by Django 5.0.3 on 2024-08-17 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0004_requestlog_delete_recipeingredient'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requestlog',
            old_name='method',
            new_name='http_method',
        ),
        migrations.RenameField(
            model_name='requestlog',
            old_name='timestamp',
            new_name='request_timestamp',
        ),
        migrations.RenameField(
            model_name='requestlog',
            old_name='url',
            new_name='request_url',
        ),
    ]
