name: Deploy Django to EC2

on:
  push:
    branches:
      - feature/actionsCICD

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install --upgrade pip
        pip install -r requirements.txt

    - name: Deploy to EC2
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        EC2_HOST: ${{ secrets.EC2_HOST }}
        EC2_USER: ${{ secrets.EC2_USER }}
      run: |
        sudo apt-get update
        sudo apt-get install -y openssh-client
        mkdir -p ~/.ssh
        echo "$SSH_PRIVATE_KEY" > ~/.ssh/deployer2.pem
        chmod 600 ~/.ssh/deployer2.pem
        ssh-keyscan $EC2_HOST >> ~/.ssh/known_hosts
        ssh -i ~/.ssh/deployer2-key.pem -o StrictHostKeyChecking=no $EC2_USER@$EC2_HOST << 'EOF'
          cd /path/to/your/project
          git pull origin feature/actionsCICD
          source venv/bin/activate
          pip install -r requirements.txt
          python /jaringobi_be/manage.py migrate
          python /jaringobi_be/manage.py collectstatic --noinput
          sudo systemctl restart gunicorn
        EOF
